<a href="https://colab.research.google.com/github/fmuranda/Machine_Learning-/blob/main/Creating_Tensors_like_other_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Creating tensors like other tensors

In [ ]:
import torch

In [ ]:
#@title Create tensor of shape (2,5) filled with ones
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
#@title Create a tensor with the same size filled with random numbers
torch.manual_seed(111)
random_tensor = torch.rand_like(starting_tensor)
random_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [ ]:
#@title Create a tensor with the same shape filled with ones
torch.ones_like(random_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#@title Create a tensor with the same shape filled with provided value
torch.full_like(random_tensor, 7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])