<a href="https://colab.research.google.com/github/fmuranda/Machine_Learning-/blob/main/Create_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#@title Tensor operations

In [8]:
import torch

In [9]:
#@title indexing 1-dim tensor example
one_dim_tensor = torch.tensor([1,2,3,4,5,6,7,8])
print(one_dim_tensor)
#print(one_dim_tensor[2].item())

tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [12]:
#@title Slicing 1-dim tensor example
#[start:end:step]
one_dim_tensor[1:4]

tensor([2, 3, 4])

In [13]:
#@title Indexing 2-dim tensor example
two_dim_tensor = torch.tensor([[1,2,3,4,5,6,],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
two_dim_tensor[1][3]

tensor(10)

In [15]:
#@title Slicing 2-dim tensor example
print("first three elements of the 1st row:",two_dim_tensor[0,0:3])
print("first four elements of the 2nd row", two_dim_tensor[1,0:4])

first three elements of the 1st row: tensor([1, 2, 3])
first four elements of the 2nd row tensor([ 7,  8,  9, 10])


In [19]:
#@title Use indexing to extract the data that meets some criteria
two_dim_tensor[two_dim_tensor<11]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#@title Combining tensors
torch.stack((two_dim_tensor,two_dim_tensor))

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [21]:
#@title Splitting tensors
first_tensor, second_tensor, third_tensor, fourth_tensor = torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5, 6]) tensor([ 7,  8,  9, 10, 11, 12]) tensor([13, 14, 15, 16, 17, 18]) tensor([19, 20, 21, 22, 23, 24])


In [22]:
#@title Splitting 2-dim tensor
torch.unbind(two_dim_tensor, dim=1)

(tensor([ 1,  7, 13, 19]),
 tensor([ 2,  8, 14, 20]),
 tensor([ 3,  9, 15, 21]),
 tensor([ 4, 10, 16, 22]),
 tensor([ 5, 11, 17, 23]),
 tensor([ 6, 12, 18, 24]))