<a href="https://colab.research.google.com/github/fmuranda/Machine_Learning-/blob/main/Creating_tensors_from_random_samples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#@title torch.rand() selects random values from a uniform distribution on the interval [0-1]
torch.manual_seed(111)
torch.rand(3,3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

In [ ]:
#@title torch.rand() selects random values from a standard normal distribution

torch.randn(4,4)

tensor([[-0.8869, -0.5960, -0.7950, -1.2043],
        [-0.5515,  0.8237,  0.1488,  0.1024],
        [ 1.3612,  0.2360, -0.8916, -1.1654],
        [-0.6134, -1.0220,  0.2255, -0.4540]])

In [ ]:
#@title torch.randin() selects random integers generated uniformly between specified low and high values

torch.randint(-1,10,(3,3))

tensor([[1, 0, 1],
        [5, 3, 1],
        [6, 7, 6]])

In [ ]:
#@title torch.randint() selects random integers generated uniformly between specified low and high values

torch.randint(1,10,(3,3))

tensor([[6, 9, 1],
        [7, 8, 4],
        [4, 4, 8]])