<a href="https://colab.research.google.com/github/fmuranda/Machine_Learning-/blob/main/Creating_Tensors_like_other_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#@title Creat a tensor of shape (2,5) filled with ones
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
#@title Create a tensor of a shape (2,5) filled with ones
torch.manual_seed(111)
rand_tensor = torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [5]:
#@title Create a tensot with the same shape filled with ones
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
#@title Create a tensor with the same shape filled with provided value
torch.full_like(starting_tensor, 7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

In [15]:
# This is how your code will be called.
# You can edit this code to try different testing cases.
import numpy as np
input_list = [[1, 5, 7, 9, 11], [13, 15, 17, 19, 21]]
input_array = np.array([[[15, 17, 11], [19, 14, 13]]])